//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int Question_ID { get; set; }
        public int Test_ID { get; set; }
        public string TestQuestion { get; set; }
        public string QA { get; set; }
        public string QB { get; set; }
        public string QC { get; set; }
        public string QAns { get; set; }
        public int QMark { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
